/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ApiKey = IDL.Record({
  'name' : IDL.Text,
  'createdDate' : Time,
  'isActive' : IDL.Bool,
});
export const UserUsageStats = IDL.Record({
  'reportsGenerated' : IDL.Nat,
  'companiesTracked' : IDL.Nat,
  'apiCallCount' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'avatarUrl' : ExternalBlob,
});
export const DashboardEntry = IDL.Record({
  'companiesTracked' : IDL.Nat,
  'dataIngestion' : IDL.Nat,
  'apiRequestCount' : IDL.Nat,
  'activeAnalyses' : IDL.Nat,
});
export const Status = IDL.Variant({
  'completed' : IDL.Null,
  'analyzing' : IDL.Null,
});
export const Report = IDL.Record({
  'status' : Status,
  'date' : Time,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createApiKey' : IDL.Func([IDL.Text], [ApiKey], []),
  'generateApiKeyForCaller' : IDL.Func([], [IDL.Text], []),
  'getCallerApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUsageStats' : IDL.Func([], [IDL.Opt(UserUsageStats)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardEntry], ['query']),
  'getReportsForCaller' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'http_request' : IDL.Func(
      [
        IDL.Record({
          'url' : IDL.Text,
          'method' : IDL.Variant({ 'get' : IDL.Null, 'post' : IDL.Null }),
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listApiKeysForCaller' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
  'regenerateApiKeyForCaller' : IDL.Func([], [IDL.Text], []),
  'saveCallerUsageStats' : IDL.Func([UserUsageStats], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ApiKey = IDL.Record({
    'name' : IDL.Text,
    'createdDate' : Time,
    'isActive' : IDL.Bool,
  });
  const UserUsageStats = IDL.Record({
    'reportsGenerated' : IDL.Nat,
    'companiesTracked' : IDL.Nat,
    'apiCallCount' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'avatarUrl' : ExternalBlob,
  });
  const DashboardEntry = IDL.Record({
    'companiesTracked' : IDL.Nat,
    'dataIngestion' : IDL.Nat,
    'apiRequestCount' : IDL.Nat,
    'activeAnalyses' : IDL.Nat,
  });
  const Status = IDL.Variant({
    'completed' : IDL.Null,
    'analyzing' : IDL.Null,
  });
  const Report = IDL.Record({
    'status' : Status,
    'date' : Time,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createApiKey' : IDL.Func([IDL.Text], [ApiKey], []),
    'generateApiKeyForCaller' : IDL.Func([], [IDL.Text], []),
    'getCallerApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUsageStats' : IDL.Func([], [IDL.Opt(UserUsageStats)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardEntry], ['query']),
    'getReportsForCaller' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'http_request' : IDL.Func(
        [
          IDL.Record({
            'url' : IDL.Text,
            'method' : IDL.Variant({ 'get' : IDL.Null, 'post' : IDL.Null }),
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listApiKeysForCaller' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
    'regenerateApiKeyForCaller' : IDL.Func([], [IDL.Text], []),
    'saveCallerUsageStats' : IDL.Func([UserUsageStats], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };